package com.shentu.gamebox.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOX_INSTALL".
*/
public class boxInstallDao extends AbstractDao<boxInstall, Long> {

    public static final String TABLENAME = "BOX_INSTALL";

    /**
     * Properties of entity boxInstall.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Agent_code = new Property(1, String.class, "agent_code", false, "AGENT_CODE");
        public final static Property Imei = new Property(2, String.class, "imei", false, "IMEI");
        public final static Property Add_time = new Property(3, int.class, "add_time", false, "ADD_TIME");
    }


    public boxInstallDao(DaoConfig config) {
        super(config);
    }
    
    public boxInstallDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOX_INSTALL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"AGENT_CODE\" TEXT," + // 1: agent_code
                "\"IMEI\" TEXT," + // 2: imei
                "\"ADD_TIME\" INTEGER NOT NULL );"); // 3: add_time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOX_INSTALL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, boxInstall entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String agent_code = entity.getAgent_code();
        if (agent_code != null) {
            stmt.bindString(2, agent_code);
        }
 
        String imei = entity.getImei();
        if (imei != null) {
            stmt.bindString(3, imei);
        }
        stmt.bindLong(4, entity.getAdd_time());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, boxInstall entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String agent_code = entity.getAgent_code();
        if (agent_code != null) {
            stmt.bindString(2, agent_code);
        }
 
        String imei = entity.getImei();
        if (imei != null) {
            stmt.bindString(3, imei);
        }
        stmt.bindLong(4, entity.getAdd_time());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public boxInstall readEntity(Cursor cursor, int offset) {
        boxInstall entity = new boxInstall( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // agent_code
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // imei
            cursor.getInt(offset + 3) // add_time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, boxInstall entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setAgent_code(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setImei(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAdd_time(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(boxInstall entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(boxInstall entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(boxInstall entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
