package com.shentu.gamebox.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.shentu.gamebox.greendao.GameData;

import com.shentu.gamebox.greendao.GameDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gameDataDaoConfig;

    private final GameDataDao gameDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gameDataDaoConfig = daoConfigMap.get(GameDataDao.class).clone();
        gameDataDaoConfig.initIdentityScope(type);

        gameDataDao = new GameDataDao(gameDataDaoConfig, this);

        registerDao(GameData.class, gameDataDao);
    }
    
    public void clear() {
        gameDataDaoConfig.clearIdentityScope();
    }

    public GameDataDao getGameDataDao() {
        return gameDataDao;
    }

}
